/* PAGE NAVIGATION */
const pages={home:$('homePage'),meal:$('mealPage'),planner:$('plannerPage'),stats:$('statsPage'),my:$('myPage')};
const navigationButtons=document.querySelectorAll('.nav-item');
function showPage(pageName){if(!pages[pageName])return;Object.values(pages).forEach(page=>{page.hidden=true;page.classList.remove('active-page');});pages[pageName].hidden=false;pages[pageName].classList.add('active-page');navigationButtons.forEach(button=>{const active=button.dataset.page===pageName;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});if(pageName==='stats')updateStatistics();if(pageName==='my')updateMyPage();window.scrollTo({top:0,behavior:'smooth'});}
navigationButtons.forEach(button=>button.addEventListener('click',()=>showPage(button.dataset.page)));
document.querySelectorAll('[data-go-page]').forEach(button=>button.addEventListener('click',()=>showPage(button.dataset.goPage)));

/* STORAGE */
function loadStorage(key,fallbackValue){try{const saved=localStorage.getItem(key);return saved===null?fallbackValue:JSON.parse(saved);}catch(error){console.error(`${key} 데이터를 불러오지 못했습니다.`,error);return fallbackValue;}}
function saveStorage(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch(error){console.error(`${key} 데이터를 저장하지 못했습니다.`,error);}}
function validObject(value){return value&&typeof value==='object'&&!Array.isArray(value);}
let todoData=loadStorage('todoData',{});if(!validObject(todoData))todoData={};
let studyData=loadStorage('studyData',{});if(!validObject(studyData))studyData={};
let sleepData=loadStorage('sleepData',{});if(!validObject(sleepData))sleepData={};

/* TODO */
const todoForm=$('todoForm'),todoInput=$('todoInput'),todoList=$('todoList'),todoCount=$('todoCount'),todoPercent=$('todoPercent'),todoProgress=$('todoProgress'),todoEmpty=$('todoEmpty'),homeTodoCount=$('homeTodoCount'),homeTodoProgress=$('homeTodoProgress'),homeTodoMessage=$('homeTodoMessage');
function getTodayTodos(){const today=koreaToday();if(!Array.isArray(todoData[today]))todoData[today]=[];return todoData[today];}
function addTodo(text){const todos=getTodayTodos();if(todos.length>=30){alert('오늘의 할 일은 최대 30개까지 등록할 수 있어요.');return;}todos.push({id:Date.now(),text:text.trim().slice(0,60),completed:false});saveStorage('todoData',todoData);renderTodos();}
function toggleTodo(id){const todo=getTodayTodos().find(item=>item.id===id);if(!todo)return;todo.completed=!todo.completed;saveStorage('todoData',todoData);renderTodos();}
function deleteTodo(id){const today=koreaToday();todoData[today]=getTodayTodos().filter(item=>item.id!==id);saveStorage('todoData',todoData);renderTodos();}
function renderTodos(){const todos=getTodayTodos();todoList.innerHTML='';todos.forEach(todo=>{const li=document.createElement('li');li.className='todo-item';if(todo.completed)li.classList.add('completed');const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.className='todo-checkbox';checkbox.checked=Boolean(todo.completed);checkbox.setAttribute('aria-label',`${todo.text} 완료 여부`);checkbox.addEventListener('change',()=>toggleTodo(todo.id));const text=document.createElement('span');text.className='todo-text';text.textContent=todo.text;const del=document.createElement('button');del.type='button';del.className='todo-delete';del.textContent='삭제';del.addEventListener('click',()=>deleteTodo(todo.id));li.append(checkbox,text,del);todoList.appendChild(li);});updateTodoSummary();}
function updateTodoSummary(){const todos=getTodayTodos(),total=todos.length,completed=todos.filter(todo=>todo.completed).length,percent=total===0?0:Math.round(completed/total*100);todoCount.textContent=`${completed} / ${total} 완료`;todoPercent.textContent=`${percent}%`;todoProgress.style.width=`${percent}%`;todoEmpty.hidden=total!==0;homeTodoCount.textContent=`${completed} / ${total}`;homeTodoProgress.style.width=`${percent}%`;homeTodoMessage.textContent=total===0?'아직 등록된 할 일이 없어요.':completed===total?'오늘 계획한 할 일을 모두 완료했어요.':`남은 할 일 ${total-completed}개`;}
todoForm.addEventListener('submit',event=>{event.preventDefault();const text=todoInput.value.trim();if(!text){todoInput.focus();return;}addTodo(text);todoInput.value='';todoInput.focus();});

/* STUDY TIMER */
let studyStartTime=null,studyTimerInterval=null,currentStudySubject=null;
const subjectSelect=$('subjectSelect'),studyTimer=$('studyTimer'),studyStatus=$('studyStatus'),currentStudySubjectText=$('currentStudySubject'),startStudyButton=$('startStudyButton'),stopStudyButton=$('stopStudyButton'),todayStudyTotal=$('todayStudyTotal'),subjectStudyList=$('subjectStudyList'),homeStudyTime=$('homeStudyTime'),homeStudyMessage=$('homeStudyMessage');
function getTodayStudyRecords(){const today=koreaToday();if(!Array.isArray(studyData[today]))studyData[today]=[];return studyData[today];}
function formatTimer(seconds){const hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60),remaining=seconds%60;return [hours,minutes,remaining].map(v=>String(v).padStart(2,'0')).join(':');}
function formatStudyDuration(seconds){const hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);return hours===0?`${minutes}분`:`${hours}시간 ${String(minutes).padStart(2,'0')}분`;}
function getCurrentStudySeconds(){return studyStartTime===null?0:Math.max(0,Math.floor((Date.now()-studyStartTime)/1000));}
function updateStudyTimerDisplay(){studyTimer.textContent=formatTimer(getCurrentStudySeconds());}
function resetActiveStudyUI(){clearInterval(studyTimerInterval);studyStartTime=null;studyTimerInterval=null;currentStudySubject=null;studyTimer.textContent='00:00:00';studyStatus.textContent='대기 중';studyStatus.classList.remove('active');currentStudySubjectText.textContent='공부를 시작해보세요.';subjectSelect.disabled=false;startStudyButton.disabled=false;stopStudyButton.disabled=true;}
function startStudy(){if(studyStartTime!==null)return;currentStudySubject=subjectSelect.value;studyStartTime=Date.now();saveStorage('activeStudy',{subject:currentStudySubject,startTime:studyStartTime});studyStatus.textContent='공부 중';studyStatus.classList.add('active');currentStudySubjectText.textContent=`${currentStudySubject} 공부 중`;startStudyButton.disabled=true;stopStudyButton.disabled=false;subjectSelect.disabled=true;updateStudyTimerDisplay();studyTimerInterval=setInterval(updateStudyTimerDisplay,1000);}
function stopStudy(){if(studyStartTime===null)return;stopStudyButton.disabled=true;const studiedSeconds=getCurrentStudySeconds();if(studiedSeconds>=1)getTodayStudyRecords().push({subject:currentStudySubject,seconds:studiedSeconds});if(studiedSeconds>=1)saveStorage('studyData',studyData);localStorage.removeItem('activeStudy');resetActiveStudyUI();updateStudySummary();}
function getTotalStudySeconds(){return getTodayStudyRecords().reduce((total,record)=>total+Number(record.seconds||0),0);}
function getSubjectStudyTimes(records=getTodayStudyRecords()){const subjects={국어:0,수학:0,영어:0,과학:0,기타:0};records.forEach(record=>{if(subjects[record.subject]!==undefined)subjects[record.subject]+=Number(record.seconds||0);});return subjects;}
function updateStudySummary(){const total=getTotalStudySeconds();todayStudyTotal.textContent=formatStudyDuration(total);homeStudyTime.textContent=formatStudyDuration(total);homeStudyMessage.textContent=total===0?'아직 오늘의 공부 기록이 없어요.':'오늘 기록된 총 공부시간이에요.';const subjectTimes=getSubjectStudyTimes();subjectStudyList.innerHTML='';Object.entries(subjectTimes).forEach(([subject,seconds])=>{const li=document.createElement('li'),name=document.createElement('span'),time=document.createElement('strong');name.textContent=subject;time.textContent=formatStudyDuration(seconds);li.append(name,time);subjectStudyList.appendChild(li);});}
function restoreActiveStudy(){const active=loadStorage('activeStudy',null);if(!active)return;const validSubject=['국어','수학','영어','과학','기타'].includes(active.subject),validStart=Number.isFinite(active.startTime)&&active.startTime<=Date.now();if(!validSubject||!validStart){localStorage.removeItem('activeStudy');return;}currentStudySubject=active.subject;studyStartTime=active.startTime;subjectSelect.value=currentStudySubject;subjectSelect.disabled=true;startStudyButton.disabled=true;stopStudyButton.disabled=false;studyStatus.textContent='공부 중';studyStatus.classList.add('active');currentStudySubjectText.textContent=`${currentStudySubject} 공부 중`;updateStudyTimerDisplay();studyTimerInterval=setInterval(updateStudyTimerDisplay,1000);}
startStudyButton.addEventListener('click',startStudy);stopStudyButton.addEventListener('click',stopStudy);

/* SLEEP */
const sleepTimeInput=$('sleepTime'),wakeTimeInput=$('wakeTime'),calculateSleepButton=$('calculateSleepButton'),sleepDuration=$('sleepDuration'),sleepHistoryList=$('sleepHistoryList'),sleepHistoryEmpty=$('sleepHistoryEmpty'),homeSleepTime=$('homeSleepTime'),homeSleepMessage=$('homeSleepMessage');
function timeToMinutes(timeString){if(!/^\d{2}:\d{2}$/.test(timeString))return null;const [hours,minutes]=timeString.split(':').map(Number);if(hours<0||hours>23||minutes<0||minutes>59)return null;return hours*60+minutes;}
function calculateSleepMinutes(sleepTime,wakeTime){const sleepMinutes=timeToMinutes(sleepTime);let wakeMinutes=timeToMinutes(wakeTime);if(sleepMinutes===null||wakeMinutes===null||wakeMinutes===sleepMinutes)return null;if(wakeMinutes<sleepMinutes)wakeMinutes+=24*60;return wakeMinutes-sleepMinutes;}
function formatSleepDuration(totalMinutes){const hours=Math.floor(totalMinutes/60),minutes=totalMinutes%60;return `${hours}시간 ${minutes}분`;}
function saveSleepRecord(){const sleepTime=sleepTimeInput.value,wakeTime=wakeTimeInput.value;if(!sleepTime||!wakeTime)return;const durationMinutes=calculateSleepMinutes(sleepTime,wakeTime);if(durationMinutes===null){sleepDuration.textContent='시간을 확인해주세요.';return;}sleepData[koreaToday()]={sleepTime,wakeTime,durationMinutes};saveStorage('sleepData',sleepData);updateSleepUI();}
function updateSleepHistory(){sleepHistoryList.innerHTML='';const recent=Object.entries(sleepData).filter(([,record])=>validObject(record)).map(([date,record])=>({date,...record})).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,7);sleepHistoryEmpty.hidden=recent.length>0;recent.forEach(record=>{const li=document.createElement('li'),date=document.createElement('span'),duration=document.createElement('strong');date.textContent=formatShortDate(record.date);duration.textContent=formatSleepDuration(Number(record.durationMinutes||0));li.append(date,duration);sleepHistoryList.appendChild(li);});}
function updateSleepUI(){const todayRecord=sleepData[koreaToday()];if(!validObject(todayRecord)){sleepDuration.textContent='기록 없음';homeSleepTime.textContent='기록 없음';homeSleepMessage.textContent='아직 오늘의 수면 기록이 없어요.';updateSleepHistory();return;}const formatted=formatSleepDuration(Number(todayRecord.durationMinutes||0));sleepDuration.textContent=formatted;homeSleepTime.textContent=formatted;homeSleepMessage.textContent=`${todayRecord.sleepTime} 취침 · ${todayRecord.wakeTime} 기상`;sleepTimeInput.value=todayRecord.sleepTime;wakeTimeInput.value=todayRecord.wakeTime;updateSleepHistory();}
calculateSleepButton.addEventListener('click',saveSleepRecord);

